ip = '127.0.0.1'
port = 80
[h1]
font = 'NanumGothic.ttf'
size = 14
[page]
# 원칙적으로 여백은 위쪽, 아래쪽, 왼쪽, 오른쪽, 머리말, 꼬리말 있읍니다.
# 지금은 모두 10으로 합니다.
margin = 10
# 아래 폰트는 페이지의 default_font 폰트입니다.
font = 'NanumGothic.ttf'
[paragraph]
# 단락 여백은 원칙적으로 여백은 위쪽, 아래쪽, 왼쪽, 오른쪽있읍니다.
# 지금은 모두 10으로 합니다.
margin = 10
# 아래 폰트는 페이지의 default_font 폰트입니다.
font = 'NanumGothic.ttf'
size = 14