[common]
# 페이지 크기(A4기준)
page_width = 210.0
page_height = 297.0
# 마진
top_margin = 
bottom_margin = 
left_margin = 
right_margin = 
# 행간
leading = 10
# 제공해주는 템플릿
font_type = default
font_default_size = 

[header]
h1_size = 
h2_size = 
h3_size = 
h4_size = 
h5_size = 
h6_size = 

