// inner = @{ char* }
// string = ${ "\"" ~ inner ~ "\"" }
// 우선 가장 평범한 문자열을 정의합니다.
// 만약 이 정의를 하지 않고 바로 아래와 같이 넣으면 
// BOLD = {("**" | "__") ~ (LETTER+ | NUMBER+) ~ ("**" | "__") }
// - PLAIN: "**" 과 같이 이것도 들어갑니다.
// 아래 것은 1자 이상의 문자 또는 숫자 또는 빈칸은 PLAIN 이라고 정의하는 것입니다.
PLAIN = {(LETTER+ | NUMBER+ | PUNCTUATION+ | " "+)}

// 문장의 형태를 정의한다.
BOLD = {("**" | "__") ~ PLAIN ~ ("**" | "__") }
ITALIC = { ("*" | "_") ~ PLAIN ~ ("*" | "_") }
SUBSCRIPT = { "<sub>" ~ PLAIN ~ "</sub>"}
SUPERSCRIPT = { "<sup>" ~ PLAIN ~ "</sup>"}

// 앞에서 정의한 문장의 형태를 포괄하는 것을 만든다.
SENTENCE = { ( BOLD | ITALIC | SUBSCRIPT | PLAIN | SUPERSCRIPT)* }

// HEADER를 정의하기 위해 세부적인 
H1 = {"#"{1} ~ " " ~ SENTENCE}
H2 = {"#"{2} ~ " " ~ SENTENCE}
H3 = {"#"{3} ~ " " ~ SENTENCE}
H4 = {"#"{4} ~ " " ~ SENTENCE}
H5 = {"#"{5} ~ " " ~ SENTENCE}

HEADER = { ( H1 | H2 | H3 | H4 | H5)}
